//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPSData
    {
        public System.Guid IdGPSData { get; set; }
        public Nullable<System.Guid> IdSession { get; set; }
        public Nullable<System.DateTime> SecondsFromStart { get; set; }
        public Nullable<int> BoatSpeed { get; set; }
        public Nullable<int> BoatDirection { get; set; }
        public Nullable<int> WindSpeed { get; set; }
        public Nullable<int> WindDirection { get; set; }
        public string GeoHeight { get; set; }
        public string GeoWidth { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
